name: Faster-1-in-2-Probability-Executor-in-Node.js
on:
  schedule:
   - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      Execution_Count:
        description: 'Execution Count'
        required: true
        default: '10000000000'
        type: string

run-name: Faster - 1 in 2 Probability Executor in Node.js ( ${{ github.event.inputs.Execution_Count || '10000000000' }} )

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run script
        run: node script.js ${{ github.event.inputs.Execution_Count || '10000000000' }}
